<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Feb_20_17_21_14_GMT_2018.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Feb_20_17_21_14_GMT_2018.jpg><img src=Tue_Feb_20_17_21_14_GMT_2018.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="BJSS Technical Test - Functional Testcases" duration-ms="11395" started-at="2018-02-20T17:21:03Z" finished-at="2018-02-20T17:21:14Z">
    <groups>
    </groups>
    <test name="Capture Screenshot Test" duration-ms="11395" started-at="2018-02-20T17:21:03Z" finished-at="2018-02-20T17:21:14Z">
      <class name="com.bjss.testcases.functional.CaptureScreenshotAfterFailTest">
        <test-method status="FAIL" signature="captureScreenshotAfterFailTest(java.util.Hashtable)[pri:0, instance:com.bjss.testcases.functional.CaptureScreenshotAfterFailTest@909217e]" name="captureScreenshotAfterFailTest" duration-ms="9415" started-at="2018-02-20T17:21:03Z" data-provider="dp" finished-at="2018-02-20T17:21:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{runmode=Y, assertFail=Spurs}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The String : Spurs is meant to differ from: POPULAR to cause an intentional fail so a screenshot can be taken! expected [Spurs] but found [POPULAR]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The String : Spurs is meant to differ from: POPULAR to cause an intentional fail so a screenshot can be taken! expected [Spurs] but found [POPULAR]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.bjss.testcases.functional.CaptureScreenshotAfterFailTest.captureScreenshotAfterFailTest(CaptureScreenshotAfterFailTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Feb_20_17_21_14_GMT_2018.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Feb_20_17_21_14_GMT_2018.jpg><img src=Tue_Feb_20_17_21_14_GMT_2018.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- captureScreenshotAfterFailTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.bjss.testcases.functional.CaptureScreenshotAfterFailTest@909217e]" name="tearDown" is-config="true" duration-ms="87" started-at="2018-02-20T17:21:14Z" finished-at="2018-02-20T17:21:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.bjss.testcases.functional.CaptureScreenshotAfterFailTest -->
    </test> <!-- Capture Screenshot Test -->
  </suite> <!-- BJSS Technical Test - Functional Testcases -->
</testng-results>
